version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5002 app:app
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - redis-db

  redis-db:
    image: "redis:alpine"
    ports:
      - "6379:6379"  # Exposing Redis on port 6380 externally
