version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5002 app:app
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

